on:
  push:
  pull_request:

name: CI

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check code formatting
        run: diff <(gofmt -d .) <(echo -n)
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18, 1.19. 1.20, 1.21, 1.22]
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Code
        uses: actions/checkout@v4
      - run: go test -v -race ./...
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Code
        uses: actions/checkout@v3
      - name: Go vet
        run: go vet -x ./...
